services:
  postgres:
    image: postgres:16
    container_name: library-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: